#!/usr/bin/env bash
# ============================================================================
# repo_creation_commands.sh
#
# Creates the public GitHub repository papanokechi/wkb-newton-polygons.
# Safe to run from the project root (the directory containing paper/,
# arxiv_bundle/, journal_bundle/, data/, ...).
#
# Requirements:
#   - gh CLI authenticated as 'papanokechi' (verified with `gh auth status`)
#   - git installed
# ============================================================================

set -euo pipefail

REPO_OWNER="papanokechi"
REPO_NAME="wkb-newton-polygons"
REPO_DESCRIPTION="A functorial classification theory of scalar linear operators with one irregular singularity: computational atlas, proofs, and camera-ready manuscript."
REPO_HOMEPAGE="https://doi.org/10.5281/zenodo.XXXXXXX"  # update after Zenodo v2.0

# ---- 1. Verify gh auth and required scopes ----------------------------------
gh auth status

# ---- 2. Create the public repository ----------------------------------------
#    --public       : world-readable
#    --description  : short tagline visible in the repo header
#    --homepage     : DOI link (Zenodo)
#    --license      : we manage LICENSE-CODE and LICENSE-TEXT manually
#                     (dual-licensed; GitHub's --license flag only supports one)
gh repo create "${REPO_OWNER}/${REPO_NAME}" \
    --public \
    --description "${REPO_DESCRIPTION}" \
    --homepage    "${REPO_HOMEPAGE}"

echo "Created https://github.com/${REPO_OWNER}/${REPO_NAME}"

# ---- 3. Add topics (searchable tags) ----------------------------------------
gh repo edit "${REPO_OWNER}/${REPO_NAME}" \
    --add-topic wkb-analysis \
    --add-topic newton-polygon \
    --add-topic stokes-phenomenon \
    --add-topic irregular-singularity \
    --add-topic levelt-turrittin \
    --add-topic classification-theory \
    --add-topic mathematical-physics \
    --add-topic computer-algebra \
    --add-topic reproducible-research

# ---- 4. Drop in repo-level metadata files -----------------------------------
# (.gitignore, README.md, CITATION.cff, CONTRIBUTING.md, CHANGELOG.md are
# generated by publication_pipeline/repo_file_contents/ and placed at the
# repo root by repo_populate_commands.sh.)

echo "Repository shell created. Run repo_populate_commands.sh next."
